// Code generated by "stringer -type=runnerType -linecomment -output=runner_type_string.go"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[amiImage-1]
	_ = x[ebsSnapshot-2]
	_ = x[rdsSnapshot-3]
	_ = x[ssmDocument-4]
}

const _runnerType_name = "AMIsnapshotsEBSsnapshotsRDSssmDocument"

var _runnerType_index = [...]uint8{0, 3, 15, 27, 38}

func (i runnerType) String() string {
	i -= 1
	if i < 0 || i >= runnerType(len(_runnerType_index)-1) {
		return "runnerType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}

	return _runnerType_name[_runnerType_index[i]:_runnerType_index[i+1]]
}
